name: Quality Minds Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout chrome
        uses: actions/checkout@v3
      - name: Cypress run chrome
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress-dashboad-chrome
      - name: Cypress run firefox
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress-dashboad-firefox
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: Cypress Quality Minds report
          path: cypress/reports/html
          retention-days: 30
