name: Quality Minds Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress tests in chrome
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress-dashboad-chrome
      - name: Run Cypress tests in firefox
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress-dashboad-firefox
      - name: "Upload Artifact"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Cypress Quality Minds report
          path: cypress/reports/html
          retention-days: 30
